import { useState } from "react";
import { generateSchedule } from "../services/geminiService";
import jsPDF from "jspdf";

function Scheduler({ tasks }) {
  const [hours, setHours] = useState("");
  const [schedule, setSchedule] = useState("");
  const [loading, setLoading] = useState(false);

  const handleGenerateSchedule = async () => {
    if (tasks.length === 0) {
      setSchedule("No tasks available.");
      return;
    }
    setLoading(true);
    const result = await generateSchedule(tasks, hours);
    setSchedule(result);
    setLoading(false);
  };

  const exportToPDF = () => {
    if (!schedule) return;

    const doc = new jsPDF();

    // Header
    doc.setFillColor(124, 58, 237);
    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("LastMinute AI — Daily Schedule", 14, 18);

    // Date
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated on ${new Date().toLocaleDateString("en-IN", {
        weekday: "long",
        day: "numeric",
        month: "long",
        year: "numeric",
      })}`,
      14,
      26
    );

    // Schedule content
    doc.setTextColor(30, 30, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");

    const lines = doc.splitTextToSize(schedule, 180);
    doc.text(lines, 14, 45);

    // Footer
    doc.setFontSize(9);
    doc.setTextColor(150, 150, 150);
    doc.text(
      "Generated by LastMinute AI — Your Productivity Companion",
      14,
      285
    );

    doc.save("LastMinute-AI-Schedule.pdf");
  };

  const copyToClipboard = () => {
    if (!schedule) return;
    navigator.clipboard.writeText(schedule);
    alert("Schedule copied to clipboard!");
  };

  return (
    <div className="scheduler">
      <h2>AI Smart Scheduler</h2>

      <div className="scheduler-controls">
        <input
          type="number"
          placeholder="Available hours today"
          value={hours}
          onChange={(e) => setHours(e.target.value)}
          min="1"
          max="24"
        />

        <button onClick={handleGenerateSchedule} disabled={loading}>
          {loading ? "Generating..." : "⚡ Generate Schedule"}
        </button>
      </div>

      {schedule && (
        <>
          <pre className="schedule-output">{schedule}</pre>

          <div className="schedule-actions">
            <button onClick={exportToPDF} className="btn-pdf">
              📄 Export as PDF
            </button>
            <button onClick={copyToClipboard} className="btn-copy">
              📋 Copy to Clipboard
            </button>
          </div>
        </>
      )}
    </div>
  );
}

export default Scheduler;